### ISSUE TITLE
Consider dual-licensing/switching to a more liberal license?

### ISSUE THREAD

**Issue by jeduan** [wscherphof/lua-loader#1]
Hi!

First of all, thanks for the awesome work, finding this library was a nice surprise. I've been working on a similar system to yours, but instead of using `npm`, I've been using `bower` since it is simpler (which was something I was looking for in case I needed to fork outright the package manager) and was easy to install [my own repository](http://yogome-bower.herokuapp.com/packages).

Anyways, the thing I'm asking is to consider granting the project/us a more liberal license (MIT/Apache would work) since there is not clear wether we can modify this library to use our `bower` repos and still comply with the LGPL on our educational [iOS](http://appstore.com/yogomeinc)/[Android](https://play.google.com/store/apps/developer?id=Yogome,+Inc.) games.

**Comment by wscherphof** [comment]
Thanks for your interest. I never used bower, curious why you'd prefer it
over npm (which appears to me as package management heaven ;-))

I don't really see how lgpl would restrict you from the modifications
you're planning, can you elaborate?

**Comment by jeduan** [comment]
Re: bower, it didn't _feel_ right to me installing the packages on the main npm repository and creating a custom bower one was a breeze. In usage, both are pretty similar, and [this discussion](https://plus.google.com/+PaulIrish/posts/cHLhcSfJyJo) could be interesting

wrt: LGPL, it seems that if you are using code on iOS, there's an LGPL clause that requires you to be able to swap implementations, but that's impossible due to sandboxing on AppStore apps. The alternative that gets thrown around is to use static linking, but that's also not really an option with Corona. [Here's a nice summary](http://multinc.com/2009/08/24/compatibility-between-the-iphone-app-store-and-the-lgpl/) of the situation. With these in mind, libraries such as [Cocos2d have been re-licensed](http://www.cocos2d-iphone.org/forums/topic/is-lgpl-really-the-best-license-option-for-the-future-of-cocos2d/) under the MIT license

**Comment by wscherphof** [comment]
Hey, this is helpful, I'll look into it

**Comment by wscherphof** [comment]
@jeduan, is this a workable solution for your ends?

**Comment by jeduan** [comment]
Totally, I appreciate your response!

**Comment by wscherphof** [comment]
Super! Glad you pointed this out, I wasn't aware.
